export const APP_NAME = "FE Boilerplate";

/** Key localStorage cho Zustand persist store app config (theme, v.v.) */
export const APP_CONFIG_STORAGE_KEY = "boilerplate-app-config";

/** Tên cookie lưu theme để server đọc (SSR, tránh FOUC Ant Design) */
export const THEME_COOKIE_NAME = "boilerplate-theme";

/** Max-age cookie theme (giây). 1 năm */
export const THEME_COOKIE_MAX_AGE = 365 * 24 * 60 * 60;

export const DEFAULT_METADATA = {
  title: "Create Next App",
  description: "Generated by create next app",
} as const;
